server:
  port: 8080
    
spring:
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update  
  datasource:
    platform: postgress
    url: ${DATABASE_URL}
    username: ${USER}
    password: ${PASSWORD}
  